name: flutter_ios_in_app_purchase
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.willcheung.flutter_ios_in_app_purchase
    pluginClass: FlutterIosInAppPurchasePlugin
